import { Product, InventoryItem, StockTransaction } from './types';

export const products: Product[] = [
  {
    id: 'prod1',
    brand: 'Jordan',
    name: 'Jordan 1 Retro High OG Spider-Man Across The Spider-Verse',
    color: 'Red/Black',
    sku: 'DV1753-601',
  },
  {
    id: 'prod2',
    brand: 'Nike',
    name: "Nike Dunk Low Retro White Black Panda (Women's)",
    color: 'White/Black',
    sku: 'DD1503-101',
  },
  {
    id: 'prod3',
    brand: 'Jordan',
    name: 'Jordan 4 Retro Red Cement',
    color: 'Red/White',
    sku: 'DH6927-161',
  },
  {
    id: 'prod4',
    brand: 'Nike',
    name: 'Nike SB Dunk Low Pro Bart Simpson',
    color: 'Yellow/Blue',
    sku: 'BQ6817-602',
  },
  {
    id: 'prod5',
    brand: 'adidas',
    name: 'adidas Yeezy Slide Flax',
    color: 'Flax',
    sku: 'FZ5896',
  },
  {
    id: 'prod6',
    brand: 'New Balance',
    name: 'New Balance 550 White Grey',
    color: 'White/Grey',
    sku: 'BB550WT1',
  },
  {
    id: 'prod7',
    brand: 'Converse',
    name: 'Converse Chuck Taylor All Star',
    color: 'Black/White',
    sku: 'M9166',
  },
  {
    id: 'prod8',
    brand: 'Vans',
    name: 'Vans Old Skool Black White',
    color: 'Black/White',
    sku: 'VN000D3HY28',
  },
  {
    id: 'prod9',
    brand: 'Puma',
    name: 'Puma Suede Classic',
    color: 'Red/White',
    sku: '352634-62',
  },
  {
    id: 'prod10',
    brand: 'Reebok',
    name: 'Reebok Club C 85',
    color: 'White/Green',
    sku: 'AR0456',
  },
];

export const inventory: InventoryItem[] = [
  {
    id: 'item1',
    productId: 'prod1',
    sku: 'DV1753-601',
    size: '6.5Y',
    condition: 'New',
    cost: 150.0,
    consigner: 'Joseph Harris',
    consignDate: '2023-05-20',
    status: 'In-Stock',
    location: 'A1',
  },
  {
    id: 'item2',
    productId: 'prod2',
    sku: 'DD1503-101',
    size: '9.5W',
    condition: 'New',
    cost: 120.0,
    consigner: 'Joseph Harris',
    consignDate: '2023-06-29',
    status: 'Returned',
    location: 'A2',
  },
  {
    id: 'item3',
    productId: 'prod3',
    sku: 'DH6927-161',
    size: '9.5M',
    condition: 'New',
    cost: 250.0,
    consigner: 'Joseph Harris',
    consignDate: '2023-09-09',
    status: 'In-Stock',
    location: 'A3',
  },
  {
    id: 'item4',
    productId: 'prod4',
    sku: 'BQ6817-602',
    size: '9M',
    condition: 'New',
    cost: 240.0,
    consigner: 'Joseph Harris',
    consignDate: '2023-08-16',
    status: 'In-Stock',
    location: 'A4',
  },
  {
    id: 'item5',
    productId: 'prod5',
    sku: 'FZ5896',
    size: '10M',
    condition: 'New',
    cost: 110.0,
    consigner: 'Joseph Harris',
    consignDate: '2023-08-16',
    status: 'In-Stock',
    location: 'A5',
  },
  {
    id: 'item6',
    productId: 'prod6',
    sku: 'BB550WT1',
    size: '8.5M',
    condition: 'Used',
    cost: 90.0,
    consigner: 'Anna Lee',
    consignDate: '2023-07-10',
    status: 'In-Stock',
    location: 'B1',
  },
  {
    id: 'item7',
    productId: 'prod7',
    sku: 'M9166',
    size: '7M',
    condition: 'New',
    cost: 60.0,
    consigner: 'Anna Lee',
    consignDate: '2023-07-12',
    status: 'Sold',
    location: 'B2',
  },
  {
    id: 'item8',
    productId: 'prod8',
    sku: 'VN000D3HY28',
    size: '9M',
    condition: 'New',
    cost: 55.0,
    consigner: 'Michael Chen',
    consignDate: '2023-07-15',
    status: 'In-Stock',
    location: 'B3',
  },
  {
    id: 'item9',
    productId: 'prod9',
    sku: '352634-62',
    size: '10M',
    condition: 'Used',
    cost: 45.0,
    consigner: 'Michael Chen',
    consignDate: '2023-07-18',
    status: 'Out-of-Stock',
    location: 'B4',
  },
  {
    id: 'item10',
    productId: 'prod10',
    sku: 'AR0456',
    size: '8M',
    condition: 'New',
    cost: 70.0,
    consigner: 'Sarah Kim',
    consignDate: '2023-07-20',
    status: 'In-Stock',
    location: 'B5',
  },
];

export const stockTransactions: StockTransaction[] = [
  {
    id: 'txn1',
    itemId: 'item1',
    type: 'in',
    quantity: 1,
    date: '2023-05-20',
    toLocation: 'A1',
    user: 'Joseph Harris',
    notes: 'Initial consignment',
  },
  {
    id: 'txn2',
    itemId: 'item2',
    type: 'return',
    quantity: 1,
    date: '2023-06-29',
    fromLocation: 'A2',
    user: 'Joseph Harris',
    notes: 'Returned to consigner',
  },
  {
    id: 'txn3',
    itemId: 'item6',
    type: 'in',
    quantity: 1,
    date: '2023-07-10',
    toLocation: 'B1',
    user: 'Anna Lee',
    notes: 'Consigned used New Balance',
  },
  {
    id: 'txn4',
    itemId: 'item7',
    type: 'out',
    quantity: 1,
    date: '2023-07-13',
    fromLocation: 'B2',
    user: 'Anna Lee',
    notes: 'Sold Converse',
  },
  {
    id: 'txn5',
    itemId: 'item8',
    type: 'in',
    quantity: 1,
    date: '2023-07-15',
    toLocation: 'B3',
    user: 'Michael Chen',
    notes: 'Consigned Vans',
  },
  {
    id: 'txn6',
    itemId: 'item9',
    type: 'out',
    quantity: 1,
    date: '2023-07-18',
    fromLocation: 'B4',
    user: 'Michael Chen',
    notes: 'Out-of-stock Puma',
  },
  {
    id: 'txn7',
    itemId: 'item10',
    type: 'in',
    quantity: 1,
    date: '2023-07-20',
    toLocation: 'B5',
    user: 'Sarah Kim',
    notes: 'Consigned Reebok',
  },
]; 